# Generated by Django 5.2.16 on 2026-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('midtrans', 'Midtrans')], default='midtrans', max_length=24, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('is_production', models.BooleanField(default=False, help_text='Centang jika menggunakan Midtrans Production.')),
                ('server_key', models.CharField(blank=True, max_length=255)),
                ('client_key', models.CharField(blank=True, max_length=255)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('http_timeout', models.PositiveIntegerField(default=15)),
                ('allowed_payments', models.TextField(default='qris,gopay,shopeepay,bca_va,bni_va,bri_va,echannel,permata_va')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
    ]
