# Generated by Django 5.2.16 on 2026-07-26 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auction_settlement'),
        ('payments', '0002_paymentgatewaysetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_holder', models.CharField(blank=True, max_length=150)),
                ('reference_id', models.CharField(max_length=120, unique=True)),
                ('payout_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_payouts', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='creator_payout', to='core.auctionsettlement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
