# Generated by Django 5.2.16 on 2026-07-27 15:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auctionsettlement_subtotal_amount_and_more'),
        ('payments', '0005_setting_xendit_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeSetting',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('listing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Persentase fee bidding, dihitung dari harga awal (starting price).', max_digits=5)),
                ('minimum_listing_fee', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Fee minimum agar listing bernilai kecil tetap menutup biaya gateway.', max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('11.00'), help_text='Tarif PPN yang ditambahkan ke fee creator dan invoice buyer.', max_digits=5)),
                ('listing_fee_due_hours', models.PositiveIntegerField(default=48, help_text='Batas waktu pembayaran fee sebelum tagihan kedaluwarsa.')),
                ('auto_payout_enabled', models.BooleanField(default=False, help_text='Kirim payout ke creator otomatis setelah invoice buyer lunas.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Fee Setting',
                'verbose_name_plural': 'Platform Fee Settings',
            },
        ),
        migrations.AddField(
            model_name='creatorpayout',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorpayout',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgatewayattempt',
            name='purpose',
            field=models.CharField(choices=[('auction_settlement', 'Pelunasan invoice buyer'), ('listing_fee', 'Fee bidding creator')], db_index=True, default='auction_settlement', max_length=24),
        ),
        migrations.AlterField(
            model_name='paymentgatewayattempt',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_attempts', to='core.auctionsettlement'),
        ),
        migrations.CreateModel(
            name='ListingFeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Harga terendah (starting price) yang menjadi dasar perhitungan fee.', max_digits=18)),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Menunggu pembayaran'), ('paid', 'Lunas'), ('expired', 'Kedaluwarsa'), ('cancelled', 'Dibatalkan')], db_index=True, default='pending', max_length=16)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_fee_invoices', to=settings.AUTH_USER_MODEL)),
                ('nft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fee_invoice', to='core.nftasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentgatewayattempt',
            name='listing_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_attempts', to='payments.listingfeeinvoice'),
        ),
        migrations.AddIndex(
            model_name='listingfeeinvoice',
            index=models.Index(fields=['creator', 'status'], name='payments_li_creator_ff80ea_idx'),
        ),
    ]
