services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn batikcraft_web.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - media_data:/app/media

volumes:
  media_data:
