# Generated by Django 5.2.16 on 2026-07-27 15:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auction_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsettlement',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nilai bid pemenang sebelum PPN.', max_digits=18),
        ),
        migrations.AddField(
            model_name='auctionsettlement',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nilai PPN yang ditagihkan kepada buyer.', max_digits=18),
        ),
        migrations.AddField(
            model_name='auctionsettlement',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.00'), help_text='Tarif PPN yang berlaku saat invoice dibuat.', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_account_holder',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_bank_code',
            field=models.CharField(blank=True, help_text='Kode channel disbursement Xendit, contoh BCA atau ID_BCA.', max_length=32),
        ),
        migrations.AlterField(
            model_name='auctionsettlement',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total yang harus dibayar buyer (subtotal + PPN).', max_digits=18),
        ),
    ]
