# Generated by Django 5.2.16 on 2026-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_settlement_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSetting',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('default_timezone', models.CharField(default='Asia/Jakarta', help_text='Zona waktu default untuk batas waktu lelang dan pembayaran.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Setting',
                'verbose_name_plural': 'Marketplace Settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_name',
            field=models.CharField(blank=True, help_text='Zona waktu tampilan pengguna. Kosongkan untuk mengikuti zona waktu default marketplace.', max_length=64),
        ),
    ]
