EXTRA_TRANSLATIONS: dict[str, dict[str, str]] = {
    "id": {
        "market.common.live_auction": "Lelang aktif",
        "market.common.current_bid": "Penawaran saat ini",
        "market.common.bids": "penawaran",
        "market.common.view": "Lihat",
        "auth.field.username": "Nama pengguna",
        "auth.field.email": "Email",
        "auth.field.display_name": "Nama tampilan",
        "auth.field.role": "Peran akun",
        "auth.field.password": "Kata sandi",
        "auth.field.password1": "Kata sandi",
        "auth.field.password2": "Konfirmasi kata sandi",
        "blog.title": "Jurnal — BatikCraft",
        "blog.eyebrow": "Jurnal BatikCraft",
        "blog.line1": "Gagasan, warisan,",
        "blog.line2": "dan karya digital.",
        "blog.empty.title": "Belum ada artikel.",
        "blog.empty.body": "Artikel dapat ditambahkan melalui dashboard admin.",
    },
    "en": {
        "market.common.live_auction": "Live auction",
        "market.common.current_bid": "Current bid",
        "market.common.bids": "bids",
        "market.common.view": "View",
        "auth.field.username": "Username",
        "auth.field.email": "Email",
        "auth.field.display_name": "Display name",
        "auth.field.role": "Account role",
        "auth.field.password": "Password",
        "auth.field.password1": "Password",
        "auth.field.password2": "Confirm password",
        "blog.title": "Journal — BatikCraft",
        "blog.eyebrow": "BatikCraft Journal",
        "blog.line1": "Ideas, heritage,",
        "blog.line2": "and digital craft.",
        "blog.empty.title": "No articles yet.",
        "blog.empty.body": "Articles can be added from the admin dashboard.",
    },
}
