"""Small session-based bilingual layer for BatikCraft templates.

The project keeps user-authored blog and marketplace content untouched while
translating the product interface between Indonesian and English.
"""

from __future__ import annotations

LANGUAGE_SESSION_KEY = "batikcraft_ui_language"
LANGUAGE_COOKIE_KEY = "batikcraft_ui_language"
LANGUAGE_COOKIE_MAX_AGE = 60 * 60 * 24 * 365
DEFAULT_LANGUAGE = "id"
SUPPORTED_LANGUAGES = {
    "id": "Bahasa Indonesia",
    "en": "English",
}

TRANSLATIONS: dict[str, dict[str, str]] = {
    "id": {
        "meta.description": "BatikCraft — studio, galeri, dan market karya batik digital Nusantara.",
        "nav.open": "Buka navigasi",
        "nav.home": "Home",
        "nav.download": "Unduh",
        "nav.nft_market": "Market NFT",
        "nav.library_market": "Market Pustaka",
        "nav.model_market": "Market Model",
        "nav.app": "Aplikasi",
        "nav.blog": "Blog",
        "nav.dashboard": "Dashboard",
        "nav.logout": "Keluar",
        "nav.login": "Masuk",
        "nav.start": "Mulai",
        "language.label": "Bahasa",
        "footer.tagline": "Merangkai warisan menuju masa depan digital.",
        "footer.explore": "Jelajahi",
        "footer.journal": "Jurnal",
        "footer.studio": "Studio",
        "footer.platform": "Platform",
        "footer.about_app": "Tentang Aplikasi",
        "footer.contact": "Kontak",
        "common.search": "Cari",
        "common.view_all": "Lihat semua →",
        "common.works": "karya",
        "common.models": "model",
        "common.by": "oleh",
        "common.price": "Harga",
        "common.category": "Kategori",
        "common.license": "Lisensi",
        "common.dimensions": "Dimensi",
        "common.creator": "Kreator",
        "common.read_article": "Baca artikel →",
        "home.title": "BatikCraft — Batik untuk Masa Depan",
        "home.hero.eyebrow": "Batik · Teknologi · Kepemilikan",
        "home.hero.line1": "Warisan yang hidup,",
        "home.hero.line2": "dikreasikan ulang.",
        "home.hero.body": "Rancang motif batik di BatikCraft Studio, terbitkan karya digital, jual aset pustaka, dan temukan kolektor melalui satu ekosistem kreatif.",
        "home.hero.download": "Unduh Studio",
        "home.hero.explore": "Jelajahi Market",
        "home.stats.design": "Berkreasi bebas",
        "home.stats.publish": "Terbitkan seketika",
        "home.stats.bid": "Transaksi transparan",
        "home.workflow.eyebrow": "Satu alur yang terhubung",
        "home.workflow.title": "Dari kanvas ke kolektor.",
        "home.workflow.craft.title": "Kreasi",
        "home.workflow.craft.body": "Buat komposisi motif, warna, dan layer di aplikasi desktop BatikCraft Studio.",
        "home.workflow.publish.title": "Publikasi",
        "home.workflow.publish.body": "Kirim karya, aset pustaka, model, dan metadata langsung ke website melalui REST API.",
        "home.workflow.collect.title": "Koleksi",
        "home.workflow.collect.body": "Tayangkan NFT, jual aset pustaka, buka lelang, dan terima penawaran dari buyer terverifikasi.",
        "home.nft.eyebrow": "Market terkurasi",
        "home.nft.title": "Karya pilihan.",
        "home.library.eyebrow": "Pustaka kreator",
        "home.library.title": "Aset siap digunakan.",
        "home.journal.title": "Cerita di balik karya.",
        "home.journal.all": "Semua artikel →",
        "home.empty.market.title": "Market sedang disiapkan.",
        "home.empty.market.body": "Karya baru akan tampil setelah dipublikasikan oleh kreator.",
        "home.empty.library.title": "Belum ada aset pustaka.",
        "home.empty.library.body": "Kreator dapat menjual ornamen atau aset raster langsung dari BatikCraft Studio.",
        "home.empty.journal.title": "Ruang cerita segera hadir",
        "home.empty.journal.body": "Publikasikan artikel pertama melalui dashboard admin.",
        "home.cta.eyebrow": "Mulai berkarya",
        "home.cta.title": "Satu ide. Seribu kemungkinan motif.",
        "home.cta.button": "Buat akun BatikCraft",
        "market.nft.title": "Market NFT — BatikCraft",
        "market.nft.eyebrow": "Marketplace Batik Digital",
        "market.nft.line1": "Koleksi karyanya.",
        "market.nft.line2": "Miliki ceritanya.",
        "market.nft.placeholder": "Cari motif, kreator, atau cerita...",
        "market.nft.live": "Lelang Aktif",
        "market.nft.empty.title": "Belum ada NFT yang ditayangkan.",
        "market.nft.empty.body": "Kreator dapat mengunggah karya dari dashboard atau BatikCraft Studio.",
        "market.library.title": "Market Pustaka — BatikCraft",
        "market.library.eyebrow": "Pustaka Aset BatikCraft",
        "market.library.line1": "Bangun lebih cepat.",
        "market.library.line2": "Tetap berkarakter.",
        "market.library.body": "Temukan ornamen, flora, fauna, objek, dan elemen raster buatan kreator untuk memperkaya komposisi batik.",
        "market.library.placeholder": "Cari aset, kategori, kreator, atau lisensi...",
        "market.library.available": "Aset Pustaka Tersedia",
        "market.library.empty.title": "Belum ada aset pustaka yang dijual.",
        "market.library.empty.body": "Pilih aset di BatikCraft Studio, lalu gunakan Marketplace → Jual Asset Pustaka sebagai NFT.",
        "market.library.badge": "Aset Pustaka",
        "market.library.open": "Lihat aset",
        "market.model.title": "Market Model — BatikCraft",
        "market.model.eyebrow": "Marketplace Model BatikCraft",
        "market.model.line1": "Latih sekali.",
        "market.model.line2": "Bagikan keahlian.",
        "market.model.body": "Temukan model LoRA BatikCraft untuk ornamen, pola, flora, fauna, dan wayang.",
        "market.model.placeholder": "Cari model, kategori, atau penjual...",
        "market.model.available": "Model Tersedia",
        "market.model.empty.title": "Belum ada model yang dijual.",
        "market.model.empty.body": "Kreator dapat mengunggah model dari BatikCraft Studio atau dashboard.",
        "app.title": "Ekosistem Aplikasi — BatikCraft",
        "app.eyebrow": "Ekosistem kreatif terhubung",
        "app.line1": "Satu karya.",
        "app.line2": "Tiga ruang kerja.",
        "app.studio.body": "Aplikasi desktop untuk membuat, melatih, dan mengekspor desain batik.",
        "app.studio.link": "Pelajari Studio →",
        "app.creator.body": "Kelola profil, NFT, aset pustaka, model, harga lelang, dan metadata.",
        "app.creator.link": "Buat akun kreator →",
        "app.buyer.body": "Temukan karya, aset pustaka, dan model serta kelola riwayat transaksi.",
        "app.buyer.link": "Masuk market →",
        "app.api.eyebrow": "Siap untuk pengembang",
        "app.api.title": "REST API untuk BatikCraft Studio.",
        "app.api.body": "Autentikasi token, unggah multipart, metadata JSON, publikasi, pembelian model, dan bidding.",
        "app.api.button": "Buka API browser",
        "download.title": "Unduh Studio — BatikCraft",
        "download.body": "Kanvas desktop untuk menyusun motif, layer, warna, komposisi, aset pustaka, dan generasi AI dengan alur modern.",
        "download.windows": "Unduh untuk Windows",
        "download.github": "Lihat di GitHub",
        "download.canvas.body": "Zoom 10–800%, ruler, grid, multi-selection, grouping, layer, dan ekspor.",
        "download.web.body": "Autentikasi akun serta unggah NFT, aset pustaka, dan model langsung ke BatikCraftWeb.",
        "download.metadata.body": "Simpan jejak project, versi aplikasi, atribut motif, lisensi, dan informasi minting.",
        "download.release": "Kanal rilis",
        "download.coming": "Installer segera tersedia.",
        "download.coming.body": "Tautan installer resmi akan tersedia pada bagian ini setelah release dibuat.",
        "auth.login.title": "Masuk — BatikCraft",
        "auth.login.eyebrow": "Selamat datang kembali",
        "auth.login.headline1": "Lanjutkan",
        "auth.login.headline2": "perjalanan kreatifmu.",
        "auth.login.body": "Satu akun untuk Dashboard Kreator, Buyer Market, dan API BatikCraft Studio.",
        "auth.login.secure": "Akses aman",
        "auth.login.heading": "Masuk BatikCraft",
        "auth.login.error": "Periksa username, password, dan kode CAPTCHA.",
        "auth.login.button": "Masuk",
        "auth.login.no_account": "Belum punya akun?",
        "auth.login.register": "Daftar sekarang",
        "auth.register.title": "Daftar — BatikCraft",
        "auth.register.eyebrow": "Bergabung dengan BatikCraft",
        "auth.register.headline1": "Berkreasi, mengoleksi,",
        "auth.register.headline2": "melestarikan budaya.",
        "auth.register.body": "Pilih Creator untuk mengunggah karya dari Studio atau Buyer untuk mengikuti lelang dan membeli produk digital.",
        "auth.register.new": "Akun baru",
        "auth.register.heading": "Buat akun",
        "auth.register.button": "Daftar",
        "auth.register.have_account": "Sudah punya akun?",
        "auth.register.login": "Masuk",
        "captcha.label": "Verifikasi manusia",
        "captcha.new": "Kode baru",
        "captcha.input": "Kode CAPTCHA",
        "captcha.help": "Masukkan lima karakter pada gambar. Huruf besar dan kecil dianggap sama.",
    },
    "en": {
        "meta.description": "BatikCraft — a studio, gallery, and marketplace for Indonesian digital batik.",
        "nav.open": "Open navigation",
        "nav.home": "Home",
        "nav.download": "Download",
        "nav.nft_market": "NFT Market",
        "nav.library_market": "Library Market",
        "nav.model_market": "Model Market",
        "nav.app": "App",
        "nav.blog": "Blog",
        "nav.dashboard": "Dashboard",
        "nav.logout": "Logout",
        "nav.login": "Login",
        "nav.start": "Get Started",
        "language.label": "Language",
        "footer.tagline": "Crafting heritage into the digital future.",
        "footer.explore": "Explore",
        "footer.journal": "Journal",
        "footer.studio": "Studio",
        "footer.platform": "Platform",
        "footer.about_app": "About the App",
        "footer.contact": "Contact",
        "common.search": "Search",
        "common.view_all": "View all →",
        "common.works": "works",
        "common.models": "models",
        "common.by": "by",
        "common.price": "Price",
        "common.category": "Category",
        "common.license": "License",
        "common.dimensions": "Dimensions",
        "common.creator": "Creator",
        "common.read_article": "Read article →",
        "home.title": "BatikCraft — Batik, Crafted for Tomorrow",
        "home.hero.eyebrow": "Batik · Technology · Ownership",
        "home.hero.line1": "Living heritage,",
        "home.hero.line2": "reimagined.",
        "home.hero.body": "Design batik motifs in BatikCraft Studio, publish digital works, sell library assets, and meet collectors through one creative ecosystem.",
        "home.hero.download": "Download Studio",
        "home.hero.explore": "Explore Markets",
        "home.stats.design": "Design freely",
        "home.stats.publish": "Publish instantly",
        "home.stats.bid": "Trade transparently",
        "home.workflow.eyebrow": "One connected workflow",
        "home.workflow.title": "From canvas to collector.",
        "home.workflow.craft.title": "Craft",
        "home.workflow.craft.body": "Build motif, color, and layer compositions in the BatikCraft Studio desktop application.",
        "home.workflow.publish.title": "Publish",
        "home.workflow.publish.body": "Send artworks, library assets, models, and metadata directly to the website through the REST API.",
        "home.workflow.collect.title": "Collect",
        "home.workflow.collect.body": "List NFTs, sell library assets, open auctions, and receive bids from verified buyers.",
        "home.nft.eyebrow": "Curated market",
        "home.nft.title": "Selected works.",
        "home.library.eyebrow": "Creator library",
        "home.library.title": "Ready-to-use assets.",
        "home.journal.title": "Stories behind the craft.",
        "home.journal.all": "All articles →",
        "home.empty.market.title": "The market is being prepared.",
        "home.empty.market.body": "New works will appear after creators publish them.",
        "home.empty.library.title": "No library assets yet.",
        "home.empty.library.body": "Creators can sell ornaments or raster assets directly from BatikCraft Studio.",
        "home.empty.journal.title": "Stories are coming soon",
        "home.empty.journal.body": "Publish the first article from the admin dashboard.",
        "home.cta.eyebrow": "Start your craft",
        "home.cta.title": "One idea. A thousand motif possibilities.",
        "home.cta.button": "Create a BatikCraft account",
        "market.nft.title": "NFT Market — BatikCraft",
        "market.nft.eyebrow": "Digital Batik Marketplace",
        "market.nft.line1": "Collect the craft.",
        "market.nft.line2": "Own the story.",
        "market.nft.placeholder": "Search motifs, creators, or stories...",
        "market.nft.live": "Live Auctions",
        "market.nft.empty.title": "No NFTs are listed yet.",
        "market.nft.empty.body": "Creators can upload works from the dashboard or BatikCraft Studio.",
        "market.library.title": "Library Market — BatikCraft",
        "market.library.eyebrow": "BatikCraft Asset Library",
        "market.library.line1": "Build faster.",
        "market.library.line2": "Keep your identity.",
        "market.library.body": "Discover creator-made ornaments, flora, fauna, objects, and raster elements to enrich batik compositions.",
        "market.library.placeholder": "Search assets, categories, creators, or licenses...",
        "market.library.available": "Available Library Assets",
        "market.library.empty.title": "No library assets are for sale yet.",
        "market.library.empty.body": "Select an asset in BatikCraft Studio, then use Marketplace → Sell Library Asset as NFT.",
        "market.library.badge": "Library Asset",
        "market.library.open": "View asset",
        "market.model.title": "Model Market — BatikCraft",
        "market.model.eyebrow": "BatikCraft Model Marketplace",
        "market.model.line1": "Train once.",
        "market.model.line2": "Share the craft.",
        "market.model.body": "Discover BatikCraft LoRA models for ornaments, patterns, flora, fauna, and wayang.",
        "market.model.placeholder": "Search models, categories, or sellers...",
        "market.model.available": "Available Models",
        "market.model.empty.title": "No models are for sale yet.",
        "market.model.empty.body": "Creators can upload models from BatikCraft Studio or the dashboard.",
        "app.title": "App Ecosystem — BatikCraft",
        "app.eyebrow": "Connected creative ecosystem",
        "app.line1": "One craft.",
        "app.line2": "Three surfaces.",
        "app.studio.body": "A desktop application for creating, training, and exporting batik designs.",
        "app.studio.link": "Explore Studio →",
        "app.creator.body": "Manage profiles, NFTs, library assets, models, auction prices, and metadata.",
        "app.creator.link": "Create a creator account →",
        "app.buyer.body": "Discover works, library assets, and models while managing transaction history.",
        "app.buyer.link": "Enter the market →",
        "app.api.eyebrow": "Developer ready",
        "app.api.title": "REST API for BatikCraft Studio.",
        "app.api.body": "Token authentication, multipart uploads, JSON metadata, publishing, model purchases, and bidding.",
        "app.api.button": "Open API browser",
        "download.title": "Download Studio — BatikCraft",
        "download.body": "A desktop canvas for motifs, layers, colors, compositions, library assets, and AI generation with a modern workflow.",
        "download.windows": "Download for Windows",
        "download.github": "View on GitHub",
        "download.canvas.body": "10–800% zoom, rulers, grids, multi-selection, grouping, layers, and export.",
        "download.web.body": "Account authentication and direct NFT, library asset, and model uploads to BatikCraftWeb.",
        "download.metadata.body": "Preserve project history, app version, motif attributes, licensing, and minting information.",
        "download.release": "Release channel",
        "download.coming": "Installer coming soon.",
        "download.coming.body": "The official installer link will appear here after a release is published.",
        "auth.login.title": "Login — BatikCraft",
        "auth.login.eyebrow": "Welcome back",
        "auth.login.headline1": "Continue your",
        "auth.login.headline2": "creative journey.",
        "auth.login.body": "One account for the Creator Dashboard, Buyer Market, and BatikCraft Studio API.",
        "auth.login.secure": "Secure access",
        "auth.login.heading": "Login to BatikCraft",
        "auth.login.error": "Check your username, password, and CAPTCHA code.",
        "auth.login.button": "Login",
        "auth.login.no_account": "No account yet?",
        "auth.login.register": "Register now",
        "auth.register.title": "Register — BatikCraft",
        "auth.register.eyebrow": "Join BatikCraft",
        "auth.register.headline1": "Create, collect,",
        "auth.register.headline2": "preserve culture.",
        "auth.register.body": "Choose Creator to upload from Studio or Buyer to join auctions and purchase digital products.",
        "auth.register.new": "New account",
        "auth.register.heading": "Create an account",
        "auth.register.button": "Register",
        "auth.register.have_account": "Already have an account?",
        "auth.register.login": "Login",
        "captcha.label": "Human verification",
        "captcha.new": "New code",
        "captcha.input": "CAPTCHA code",
        "captcha.help": "Enter the five characters shown. The code is case-insensitive.",
    },
}


def normalize_language(value: object) -> str:
    language = str(value or "").strip().lower()
    return language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def get_request_language(request: object) -> str:
    """Resolve the interface language from the session, then the cookie.

    Logging in as a different user flushes the session, so the cookie keeps
    the visitor's choice from silently resetting to Indonesian.
    """

    session = getattr(request, "session", {})
    chosen = session.get(LANGUAGE_SESSION_KEY)
    if chosen is None:
        cookies = getattr(request, "COOKIES", {}) or {}
        chosen = cookies.get(LANGUAGE_COOKIE_KEY)
    return normalize_language(chosen)


def text(language: str, key: str) -> str:
    normalized = normalize_language(language)
    return TRANSLATIONS.get(normalized, {}).get(
        key,
        TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key),
    )


def language_context(request: object) -> dict[str, object]:
    language = get_request_language(request)
    return {
        "ui_language": language,
        "ui_languages": SUPPORTED_LANGUAGES,
    }
