"""Interface strings for public pages, extracted from the templates."""

PAGE_TRANSLATIONS: dict[str, dict[str, str]] = {
    "id": {
        "blog_list.new_stories_will_appear_here": "Cerita baru akan muncul di sini.",
        "blog_list.no_articles_yet": "Belum ada artikel.",
        "blog_list.read_article": "Baca artikel",
        "blog_list.search_articles": "Cari artikel...",
        "blog_list.stories_behind_the_craft": "Cerita di balik<br><em>karya.</em>",
        "buyer.bid": "Tawar",
        "buyer.highest_bid": "Bid tertinggi",
        "buyer.open_auction": "Lelang terbuka",
        "buyer.view_all": "Lihat semua",
        "buyer.view_website": "Lihat website",
        "creator.view_website": "Lihat website",
        "documentation.authenticate_studio_upload_works_publish_n": "Autentikasi Studio, unggah karya, publish NFT, dan kirim bidding melalui REST API.",
        "documentation.build_create_and_connect_with_clear_guidan": "Bangun, berkarya, dan terhubung<br><em>dengan panduan yang jelas.</em>",
        "documentation.desktop_builds": "Build Desktop",
        "documentation.documentation": "Dokumentasi",
        "documentation.documentation_for_batikcraft_studio_deskto": "Dokumentasi BatikCraft Studio, installer desktop, format proyek, dan API web dalam satu tempat.",
        "documentation.download_studio": "Unduh Studio",
        "documentation.download_the_latest_native_installer_for_y": "Unduh installer native terbaru untuk sistem operasimu.",
        "documentation.installation_details_for_windows_linux_int": "Detail instalasi untuk Windows, Linux, Mac Intel, dan Mac Apple Silicon.",
        "documentation.open_studio_guide": "Buka panduan Studio",
        "documentation.product_overview_local_setup_features_road": "Ringkasan produk, setup lokal, fitur, roadmap, dan alur kerja aplikasi desktop.",
        "documentation.project_format": "Format Proyek",
        "documentation.read_api_documentation": "Baca dokumentasi API",
        "documentation.read_installer_documentation": "Baca dokumentasi installer",
        "documentation.read_project_specification": "Baca spesifikasi proyek",
        "documentation.ready_to_start_creating": "Siap mulai berkarya?",
        "documentation.understand_the_editable_project_structure": "Pelajari struktur proyek editable, metadata, aset, dan aturan kompatibilitas.",
        "download.choose_platform": "Pilih Platform",
        "download.choose_the_installer_that_matches_your_ope": "Pilih installer sesuai sistem operasi. Setiap tombol selalu mengikuti rilis BatikCraft Studio terbaru yang dipublikasikan.",
        "download.choose_your_platform": "Pilih platformmu",
        "download.deb_installer_built_for_64_bit_ubuntu_and": "Installer DEB untuk distribusi Ubuntu dan Debian-compatible 64-bit.",
        "download.dmg_installer_for_apple_silicon_devices_in": "Installer DMG untuk perangkat Apple Silicon, termasuk M1, M2, M3, dan generasi berikutnya.",
        "download.dmg_installer_for_intel_based_mac_computer": "Installer DMG untuk komputer Mac berbasis Intel dengan arsitektur x64.",
        "download.download_the_studio_for_your_computer": "Unduh studio<br><em>untuk komputermu.</em>",
        "download.installer_exe_for_64_bit_windows_installs": "Installer EXE untuk Windows 64-bit. Terpasang per pengguna tanpa akses administrator.",
        "download.latest_release": "Rilis Terbaru",
        "download.native_installers": "Installer native",
        "download.these_links_use_github_s_latest_release_en": "Tautan ini memakai endpoint <strong>latest release</strong> GitHub sehingga otomatis mengikuti installer terbaru dengan nama berkas platform yang sama.",
        "download.view_all_releases": "Lihat semua rilis",
        "download.windows_linux_intel_mac_and_apple_silicon": "Windows, Linux, Mac Intel, dan Mac Apple Silicon tersedia sebagai paket native terpisah.",
        "home.a_marketplace_connecting_artisans_digital": "Marketplace yang menghubungkan perajin, seniman digital, kolektor, dan pengembang AI.",
        "home.a_new_generation_of_digital_batik_that_res": "Generasi baru batik digital yang tetap menghormati akar budaya.",
        "home.batik_bird_and_floral_illustration": "Ilustrasi burung dan bunga batik",
        "home.batik_technology_ownership": "Batik · Teknologi · Kepemilikan",
        "home.batikcraft_studio_nft_marketplace_asset_li": "BatikCraft Studio, marketplace NFT, pustaka aset, dan training AI lokal bekerja sebagai satu ekosistem.",
        "home.digital_batik_works_auctions_bidding_and_c": "Karya batik digital, lelang, bidding, dan kepemilikan kreatif.",
        "home.download_studio": "Unduh Studio",
        "home.explore_collection": "Jelajahi Koleksi",
        "home.heritage_for_everyone": "Warisan untuk<br><em>Semua Orang</em>",
        "home.latest_news_stories": "Berita &amp; Cerita Terbaru",
        "home.lora_models_and_local_ai_packages_for_bati": "Model LoRA dan paket AI lokal untuk memperkaya BatikCraft Studio.",
        "home.meet_our_creators": "Temui Kreator Kami",
        "home.our_collection": "Koleksi Kami",
        "home.reusable_ornaments_flora_fauna_and_creator": "Ornamen, flora, fauna, dan aset siap pakai dari kreator.",
        "home.three_marketplaces_connected_directly_to_b": "Tiga marketplace yang terhubung langsung dengan BatikCraft Studio.",
        "home.timeless_batik_and_kebaya_reimagined_for_t": "Batik dan kebaya abadi, dikreasikan ulang untuk perjalanan kreatif hari ini.",
        "library_market.build_with_heritage_assets": "Berkarya dengan<br><em>aset warisan.</em>",
        "login.captcha_protects_your_account_from_automat": "CAPTCHA aktif untuk melindungi akun dari akses otomatis.",
        "login.continue_creating_and_managing_your_digita": "Lanjutkan berkarya dan kelola ekosistem batik digitalmu.",
        "login.homepage": "Beranda",
        "login.login": "Masuk",
        "login.login_to_batikcraft": "Masuk ke BatikCraft",
        "login.username_or_email": "Username atau email",
        "market.collect_digital_heritage": "Koleksi warisan<br><em>digital.</em>",
        "market.discover_complete_batik_artworks_transpare": "Temukan karya batik utuh, lelang transparan, dan budaya yang dimiliki kreator.",
        "model_market.train_create_and_preserve": "Latih, ciptakan,<br><em>dan lestarikan.</em>",
        "news.news_batikcraft": "Berita — BatikCraft",
        "news.news_culture_and_creative_technology": "Berita, budaya,<br><em>dan teknologi kreatif.</em>",
        "news.product_updates_and_cultural_stories_will": "Pembaruan produk dan cerita budaya akan muncul di sini.",
        "news.search_news": "Cari berita...",
        "newsletter.be_the_first_to_hear_about_new_collections": "Jadilah yang pertama mengetahui koleksi baru, rilis eksklusif, dan cerita BatikCraft.",
        "newsletter.join_our_world": "Bergabung dengan Dunia Kami",
        "register.create_a_batikcraft_account": "Buat akun BatikCraft",
        "register.create_account": "Buat Akun",
        "register.homepage": "Beranda",
        "register.one_account_for_studio_creator_publishing": "Satu akun untuk Studio, publikasi kreator, dan mengoleksi karya.",
        "shell.collect_complete_digital_works": "Koleksi karya digital utuh",
        "shell.crafting_heritage_into_the_digital_future": "Membawa warisan menuju masa depan digital.",
        "shell.creator_trained_ai_models": "Model AI hasil training kreator",
        "shell.documentation": "Dokumentasi",
        "shell.reusable_motifs_and_ornaments": "Motif dan ornamen siap pakai",
    },
    "en": {
        "blog_list.new_stories_will_appear_here": "New stories will appear here.",
        "blog_list.no_articles_yet": "No articles yet.",
        "blog_list.read_article": "Read article",
        "blog_list.search_articles": "Search articles...",
        "blog_list.stories_behind_the_craft": "Stories behind<br><em>the craft.</em>",
        "buyer.bid": "Bid",
        "buyer.highest_bid": "Highest bid",
        "buyer.open_auction": "Open auction",
        "buyer.view_all": "View all",
        "buyer.view_website": "View website",
        "creator.view_website": "View website",
        "documentation.authenticate_studio_upload_works_publish_n": "Authenticate Studio, upload works, publish NFTs, and submit bids through the REST API.",
        "documentation.build_create_and_connect_with_clear_guidan": "Build, create, and connect<br><em>with clear guidance.</em>",
        "documentation.desktop_builds": "Desktop Builds",
        "documentation.documentation": "Documentation",
        "documentation.documentation_for_batikcraft_studio_deskto": "Documentation for BatikCraft Studio, desktop installers, project formats, and the web API in one place.",
        "documentation.download_studio": "Download Studio",
        "documentation.download_the_latest_native_installer_for_y": "Download the latest native installer for your operating system.",
        "documentation.installation_details_for_windows_linux_int": "Installation details for Windows, Linux, Intel Mac, and Apple Silicon Mac.",
        "documentation.open_studio_guide": "Open Studio guide",
        "documentation.product_overview_local_setup_features_road": "Product overview, local setup, features, roadmap, and the desktop workflow.",
        "documentation.project_format": "Project Format",
        "documentation.read_api_documentation": "Read API documentation",
        "documentation.read_installer_documentation": "Read installer documentation",
        "documentation.read_project_specification": "Read project specification",
        "documentation.ready_to_start_creating": "Ready to start creating?",
        "documentation.understand_the_editable_project_structure": "Understand the editable project structure, metadata, assets, and compatibility rules.",
        "download.choose_platform": "Choose Platform",
        "download.choose_the_installer_that_matches_your_ope": "Choose the installer that matches your operating system. Every button follows the newest published BatikCraft Studio release.",
        "download.choose_your_platform": "Choose your platform",
        "download.deb_installer_built_for_64_bit_ubuntu_and": "DEB installer built for 64-bit Ubuntu and Debian-compatible distributions.",
        "download.dmg_installer_for_apple_silicon_devices_in": "DMG installer for Apple Silicon devices, including M1, M2, M3, and newer chips.",
        "download.dmg_installer_for_intel_based_mac_computer": "DMG installer for Intel-based Mac computers using the x64 architecture.",
        "download.download_the_studio_for_your_computer": "Download the studio<br><em>for your computer.</em>",
        "download.installer_exe_for_64_bit_windows_installs": "Installer EXE for 64-bit Windows. Installs per user without administrator access.",
        "download.latest_release": "Latest Release",
        "download.native_installers": "Native installers",
        "download.these_links_use_github_s_latest_release_en": "These links use GitHub's <strong>latest release</strong> endpoint, so they automatically follow the newest published installer with the same platform filename.",
        "download.view_all_releases": "View all releases",
        "download.windows_linux_intel_mac_and_apple_silicon": "Windows, Linux, Intel Mac, and Apple Silicon Mac are provided as separate native packages.",
        "home.a_marketplace_connecting_artisans_digital": "A marketplace connecting artisans, digital artists, collectors, and AI developers.",
        "home.a_new_generation_of_digital_batik_that_res": "A new generation of digital batik that respects its cultural roots.",
        "home.batik_bird_and_floral_illustration": "Batik bird and floral illustration",
        "home.batik_technology_ownership": "Batik · Technology · Ownership",
        "home.batikcraft_studio_nft_marketplace_asset_li": "BatikCraft Studio, NFT marketplace, asset library, and local AI training work as one ecosystem.",
        "home.digital_batik_works_auctions_bidding_and_c": "Digital batik works, auctions, bidding, and creative ownership.",
        "home.download_studio": "Download Studio",
        "home.explore_collection": "Explore Collection",
        "home.heritage_for_everyone": "Heritage for<br><em>Everyone</em>",
        "home.latest_news_stories": "Latest News &amp; Stories",
        "home.lora_models_and_local_ai_packages_for_bati": "LoRA models and local AI packages for BatikCraft Studio.",
        "home.meet_our_creators": "Meet Our Creators",
        "home.our_collection": "Our Collection",
        "home.reusable_ornaments_flora_fauna_and_creator": "Reusable ornaments, flora, fauna, and creator assets.",
        "home.three_marketplaces_connected_directly_to_b": "Three marketplaces connected directly to BatikCraft Studio.",
        "home.timeless_batik_and_kebaya_reimagined_for_t": "Timeless batik and kebaya, reimagined for today's creative journey.",
        "library_market.build_with_heritage_assets": "Build with<br><em>heritage assets.</em>",
        "login.captcha_protects_your_account_from_automat": "CAPTCHA protects your account from automated access.",
        "login.continue_creating_and_managing_your_digita": "Continue creating and managing your digital batik ecosystem.",
        "login.homepage": "Homepage",
        "login.login": "Login",
        "login.login_to_batikcraft": "Login to BatikCraft",
        "login.username_or_email": "Username or email",
        "market.collect_digital_heritage": "Collect digital<br><em>heritage.</em>",
        "market.discover_complete_batik_artworks_transpare": "Discover complete batik artworks, transparent auctions, and creator-owned culture.",
        "model_market.train_create_and_preserve": "Train, create,<br><em>and preserve.</em>",
        "news.news_batikcraft": "News — BatikCraft",
        "news.news_culture_and_creative_technology": "News, culture,<br><em>and creative technology.</em>",
        "news.product_updates_and_cultural_stories_will": "Product updates and cultural stories will appear here.",
        "news.search_news": "Search news...",
        "newsletter.be_the_first_to_hear_about_new_collections": "Be the first to hear about new collections, exclusive releases, and BatikCraft stories.",
        "newsletter.join_our_world": "Join Our World",
        "register.create_a_batikcraft_account": "Create a BatikCraft account",
        "register.create_account": "Create Account",
        "register.homepage": "Homepage",
        "register.one_account_for_studio_creator_publishing": "One account for Studio, creator publishing, and collecting.",
        "shell.collect_complete_digital_works": "Collect complete digital works",
        "shell.crafting_heritage_into_the_digital_future": "Crafting heritage into the digital future.",
        "shell.creator_trained_ai_models": "Creator-trained AI models",
        "shell.documentation": "Documentation",
        "shell.reusable_motifs_and_ornaments": "Reusable motifs and ornaments",
    },
}
