DASHBOARD_TRANSLATIONS: dict[str, dict[str, str]] = {
    "id": {
        "role.creator": "Kreator",
        "role.buyer": "Buyer",
        "dashboard.creator.title": "Dashboard Kreator — BatikCraft",
        "dashboard.creator.workspace": "Ruang Kerja Kreator",
        "dashboard.creator.collection": "Koleksi &amp; Model",
        "dashboard.profile": "Profil",
        "dashboard.creator.archive": "Arsip digital Anda.",
        "dashboard.creator.sell_model": "Jual Model",
        "dashboard.creator.add_nft": "Tambah NFT",
        "dashboard.creator.total_works": "Total karya",
        "dashboard.creator.live_nft": "NFT aktif",
        "dashboard.creator.total_bids": "Total penawaran",
        "dashboard.creator.model_sales": "Penjualan model",
        "dashboard.creator.nft_from_studio": "NFT dari Studio",
        "dashboard.table.work": "Karya",
        "dashboard.table.status": "Status",
        "dashboard.table.price_bid": "Harga / Penawaran",
        "dashboard.table.project_id": "Project ID",
        "dashboard.table.action": "Aksi",
        "dashboard.table.base": "Base",
        "dashboard.table.version": "Versi",
        "dashboard.table.price": "Harga",
        "dashboard.table.sales": "Penjualan",
        "dashboard.view": "Lihat",
        "dashboard.publish": "Publikasikan",
        "dashboard.creator.empty_work": "Belum ada karya.",
        "dashboard.creator.empty_work_body": "Unggah manual atau kirim melalui BatikCraft Studio.",
        "dashboard.creator.empty_model": "Belum ada model. Unggah dari Studio atau dashboard.",
        "dashboard.buyer.title": "Dashboard Buyer — BatikCraft",
        "dashboard.buyer.workspace": "Ruang Kerja Kolektor",
        "dashboard.buyer.overview": "Ringkasan",
        "dashboard.buyer.heading": "Koleksi karya yang bermakna.",
        "dashboard.buyer.explore_models": "Jelajahi model",
        "dashboard.buyer.explore_nft": "Jelajahi NFT",
        "dashboard.buyer.explore_library": "Jelajahi pustaka",
        "dashboard.buyer.live_auctions": "Lelang aktif",
        "dashboard.buyer.no_auction": "Belum ada lelang aktif.",
        "dashboard.buyer.latest_bids": "Penawaran terbaru Anda",
        "dashboard.table.creator": "Kreator",
        "dashboard.table.amount": "Nominal",
        "dashboard.table.time": "Waktu",
        "dashboard.buyer.no_bid": "Anda belum melakukan penawaran.",
        "dashboard.buyer.model_library": "Pustaka Model",
        "dashboard.table.seller": "Penjual",
        "dashboard.table.license": "Lisensi",
        "dashboard.download": "Unduh",
        "dashboard.buyer.no_model": "Belum ada model di pustaka.",
        "profile.title": "Profil — BatikCraft",
        "profile.eyebrow": "Pengaturan akun",
        "profile.heading": "Profil BatikCraft.",
        "profile.body": "Informasi ini ditampilkan pada karya dan aktivitas market Anda.",
        "profile.save": "Simpan profil",
        "form.creator_workspace": "Ruang kerja kreator",
        "form.nft.body": "Karya akan tersimpan sebagai draft. Anda dapat mempublikasikannya setelah gambar dan harga awal tersedia.",
        "form.save_draft": "Simpan draft",
        "form.model.market": "Marketplace Model",
        "detail.created_by": "Dibuat oleh",
        "detail.default_description": "Karya batik digital dari BatikCraft Studio.",
        "detail.current_price": "Harga saat ini",
        "detail.saved_bids": "penawaran tersimpan",
        "detail.place_bid": "Ajukan penawaran",
        "detail.login_bid": "Masuk untuk menawar",
        "detail.not_minted": "Belum dicetak",
        "detail.bid_history": "Riwayat penawaran",
        "detail.no_bid": "Belum ada penawaran. Jadilah kolektor pertama.",
        "detail.library_asset": "Aset Pustaka",
    },
    "en": {
        "role.creator": "Creator",
        "role.buyer": "Buyer",
        "dashboard.creator.title": "Creator Dashboard — BatikCraft",
        "dashboard.creator.workspace": "Creator Workspace",
        "dashboard.creator.collection": "Collection &amp; Models",
        "dashboard.profile": "Profile",
        "dashboard.creator.archive": "Your digital archive.",
        "dashboard.creator.sell_model": "Sell Model",
        "dashboard.creator.add_nft": "Add NFT",
        "dashboard.creator.total_works": "Total works",
        "dashboard.creator.live_nft": "Live NFTs",
        "dashboard.creator.total_bids": "Total bids",
        "dashboard.creator.model_sales": "Model sales",
        "dashboard.creator.nft_from_studio": "NFTs from Studio",
        "dashboard.table.work": "Work",
        "dashboard.table.status": "Status",
        "dashboard.table.price_bid": "Price / Bid",
        "dashboard.table.project_id": "Project ID",
        "dashboard.table.action": "Action",
        "dashboard.table.base": "Base",
        "dashboard.table.version": "Version",
        "dashboard.table.price": "Price",
        "dashboard.table.sales": "Sales",
        "dashboard.view": "View",
        "dashboard.publish": "Publish",
        "dashboard.creator.empty_work": "No works yet.",
        "dashboard.creator.empty_work_body": "Upload manually or send them through BatikCraft Studio.",
        "dashboard.creator.empty_model": "No models yet. Upload from Studio or the dashboard.",
        "dashboard.buyer.title": "Buyer Dashboard — BatikCraft",
        "dashboard.buyer.workspace": "Collector Workspace",
        "dashboard.buyer.overview": "Overview",
        "dashboard.buyer.heading": "Collect meaningful craft.",
        "dashboard.buyer.explore_models": "Explore models",
        "dashboard.buyer.explore_nft": "Explore NFTs",
        "dashboard.buyer.explore_library": "Explore library",
        "dashboard.buyer.live_auctions": "Live auctions",
        "dashboard.buyer.no_auction": "No active auctions yet.",
        "dashboard.buyer.latest_bids": "Your latest bids",
        "dashboard.table.creator": "Creator",
        "dashboard.table.amount": "Amount",
        "dashboard.table.time": "Time",
        "dashboard.buyer.no_bid": "You have not placed any bids yet.",
        "dashboard.buyer.model_library": "Model Library",
        "dashboard.table.seller": "Seller",
        "dashboard.table.license": "License",
        "dashboard.download": "Download",
        "dashboard.buyer.no_model": "There are no models in your library yet.",
        "profile.title": "Profile — BatikCraft",
        "profile.eyebrow": "Account settings",
        "profile.heading": "Your BatikCraft profile.",
        "profile.body": "This information appears on your works and marketplace activity.",
        "profile.save": "Save profile",
        "form.creator_workspace": "Creator workspace",
        "form.nft.body": "The work will be saved as a draft. You can publish it after adding an image and starting price.",
        "form.save_draft": "Save draft",
        "form.model.market": "Model Marketplace",
        "detail.created_by": "Created by",
        "detail.default_description": "A digital batik work from BatikCraft Studio.",
        "detail.current_price": "Current price",
        "detail.saved_bids": "saved bids",
        "detail.place_bid": "Place bid",
        "detail.login_bid": "Login to bid",
        "detail.not_minted": "Not minted yet",
        "detail.bid_history": "Bid history",
        "detail.no_bid": "No bids yet. Be the first collector.",
        "detail.library_asset": "Library Asset",
    },
}
